version: '3.8'

services:
  web:
    build: .
    container_name: messenger_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app

  alembic:
    build: .
    container_name: alembic_messenger_migrations
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/messenger
    working_dir: /messenger
    command: alembic upgrade head  

  db:
    image: postgres:13
    container_name: messenger_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
